import enum


class IdeaStatus(str, enum.Enum):
    RAW = "RAW"
    DEVELOPING = "DEVELOPING"
    DRAFT = "DRAFT"
    READY = "READY"
    ARCHIVED = "ARCHIVED"


class PlatformType(str, enum.Enum):
    YOUTUBE = "YOUTUBE"
    INSTAGRAM = "INSTAGRAM"
    LINKEDIN = "LINKEDIN"
    GENERAL = "GENERAL"


class ContentTypeEnum(str, enum.Enum):
    YOUTUBE_VIDEO = "YOUTUBE_VIDEO"
    YOUTUBE_SHORT = "YOUTUBE_SHORT"
    INSTAGRAM_REEL = "INSTAGRAM_REEL"
    INSTAGRAM_CAROUSEL = "INSTAGRAM_CAROUSEL"
    INSTAGRAM_STORY = "INSTAGRAM_STORY"
    LINKEDIN_POST = "LINKEDIN_POST"
    LINKEDIN_DOCUMENT = "LINKEDIN_DOCUMENT"
    OTHER = "OTHER"


class ContentStatus(str, enum.Enum):
    DRAFT = "DRAFT"
    READY_TO_RECORD = "READY_TO_RECORD"
    RECORDED = "RECORDED"
    EDITED = "EDITED"
    SCHEDULED = "SCHEDULED"
    PUBLISHED = "PUBLISHED"
    ARCHIVED = "ARCHIVED"


class LineageType(str, enum.Enum):
    INSPIRED_BY = "INSPIRED_BY"
    DERIVED_FROM = "DERIVED_FROM"
    REPURPOSED_FROM = "REPURPOSED_FROM"
    RELATED_TO = "RELATED_TO"
    EXPANDS_ON = "EXPANDS_ON"
